/* Dependency-free field demo. Set USE_LIVE_API to true to opt into the documented API. */
const USE_LIVE_API = false;
const API_BASE = "";
const DEMO_DATA = {
  scene_id: "scene_0123456789abcdef", water_body_id: "demo-lake", source: "offline satellite scene", acquisition_date: "2026-09-22",
  risk: { activity: { score: 1, label: "red" } }, quality: { pixels_analyzed: 4096, water_coverage: 1, turbidity_ntu: 69.2857, chlorophyll_a_ug_l: 60.4545, quality_uncertainty: .125, ndci_mean: .30131 },
  explanation: { summary: "High harmful-algal-bloom screening signal for Demo Lake community.", band_signals: [{ band: "B02", signal: "blue water-color response" }, { band: "B03", signal: "green water-color response" }, { band: "B04", signal: "red bloom response" }, { band: "B05", signal: "red-edge spike" }] },
  alerts: { en: { severity: "red", title: "Water watch: high concern", message: "A high harmful-algal-bloom screening signal was detected for Demo Lake. Do not swim, drink untreated water, or harvest food from the affected water.", action: "Keep people and animals away and contact the local health or water authority for confirmation." }, sw: { severity: "red", title: "Uangalizi wa maji: hatari kubwa", message: "Ishara kubwa ya mwani hatari imegunduliwa katika Demo Lake. Usiogelee, usinywe maji yasiyotibiwa, wala usivune chakula kutoka maji haya.", action: "Waweke watu na wanyama mbali na maji hayo na wasiliana na mamlaka ya afya au maji kwa uthibitisho." } }
};
const NETWORK_DEMO = { propagation: [{ node_id: "node-downstream-2", hops: 1, risk_score: .86, state: "UNSAFE", uncertainty_state: "FIELD SAMPLE REQUIRED", rationale: "Downstream proximity to the flagged intake." }], alternatives: [{ node_id: "node-safe-3", name: "Chisomo borehole", distance_km: 2, safety_state: "SAFE", rationale: "Nearest safe alternative in demo records." }] };
const PRESENTER_BEATS = [
  { id: "voice", label: "VOICE", title: "Reach the community where it is", copy: "The alert is ready to travel offline: a bilingual SMS payload plus a Chichewa call-in script in the Chipatala Cha Pa Foni pattern." },
  { id: "verify-source", label: "HANDS", title: "Verify source", copy: "A field responder accepts the first task before any escalation. Status moves from pending to in-progress." },
  { id: "sample-suspect", label: "HANDS", title: "Sample suspect", copy: "The suspect source is sampled and held for laboratory confirmation. The screen remains a proxy until that evidence arrives." },
  { id: "confirm-alternative", label: "HANDS", title: "Confirm alternative", copy: "A verified-safe alternative is confirmed before the community is rerouted." },
  { id: "verify", label: "VERIFY", title: "Grade the alert after action", copy: "The response is graded against the outcome: a HIT with three weeks of lead time." },
  { id: "memory", label: "MEMORY 2.0", title: "Feed the outcome back into risk", copy: "Following weeks become training memory: the model records what worked and updates the next risk score." }
];
let language = "en", networkStep = 0, beatIndex = -1, demoRunning = false;
const $ = selector => document.querySelector(selector), $$ = selector => document.querySelectorAll(selector);
function toast(message) { const el = $("#toast"); el.textContent = message; el.classList.add("show"); clearTimeout(toast.timer); toast.timer = setTimeout(() => el.classList.remove("show"), 2800); }
function render(data = DEMO_DATA) {
  const alert = data.alerts[language], quality = data.quality, explanation = data.explanation;
  $("#alert-title").textContent = alert.title; $("#alert-message").textContent = alert.message; $("#action-copy").textContent = alert.action; $("#summary").textContent = explanation.summary; $("#source").textContent = data.source; $("#risk").textContent = Number(data.risk.activity.score).toFixed(2);
  $("#signals").innerHTML = explanation.band_signals.map(x => `<li><b>${x.band}</b> ${x.signal}</li>`).join("");
  $("#date").textContent = new Date(`${data.acquisition_date}T00:00:00Z`).toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric", timeZone: "UTC" }).toUpperCase();
  $("#connection").className = `status ${USE_LIVE_API ? "live" : "offline"}`; $("#connection").innerHTML = `<i></i> ${USE_LIVE_API ? "Live API" : "Offline demo"}`;
}
function selectView(view) { $$(".nav").forEach(x => x.classList.toggle("active", x.dataset.view === view)); $$(".view").forEach(x => { const on = x.dataset.panel === view; x.classList.toggle("visible", on); x.hidden = !on; }); const titles = { overview: "Demo Lake at a glance", signal: "Water signal, unpacked", network: "Network alert propagation", health: "Water signal to human action" }; $("#title").textContent = titles[view]; }
async function liveJson(path, options = {}) { const response = await fetch(`${API_BASE}${path}`, { ...options, headers: { "Content-Type": "application/json", ...(options.headers || {}) } }); if (!response.ok) throw new Error(`HTTP ${response.status}`); return response.json(); }
async function loadData() { if (!USE_LIVE_API) return DEMO_DATA; try { return await liveJson("/risk/demo-lake"); } catch (error) { toast(`Live API unavailable (${error.message}); showing the last valid demo panel.`); return DEMO_DATA; } }
function renderNetwork(state, detail = "") { const panel = $("#network-panel"), title = $("#network-title"), copy = $("#network-copy"), result = $("#network-result"); panel.dataset.state = state; result.hidden = true; const text = { idle: ["Ready when you are", "Press the DEMO button to build and analyze the sample network."], loading: ["Building network...", "POST /network/build then POST /network/analyze"], ready: ["Propagation found", "One downstream point is unsafe; one verified-safe alternative is available."], empty: ["No propagation found", "The network is valid, but no downstream propagation was returned."], validation: ["Validation error", "HTTP 422: network records are required."], "not-found": ["Network unavailable", "HTTP 404: no analysis found for network-demo-lake-1."], error: ["API unavailable", "Network request failed after retry; existing analysis UI is preserved."] }; [title.textContent, copy.textContent] = [text[state]?.[0] || text.error[0], detail || text[state]?.[1] || text.error[1]]; if (state === "ready") { result.hidden = false; result.innerHTML = `<div class="result-block"><b>PROPAGATION</b><ul><li>node-downstream-2 - ${NETWORK_DEMO.propagation[0].state}</li><li>${NETWORK_DEMO.propagation[0].uncertainty_state}</li></ul></div><div class="result-block"><b>ALTERNATIVE</b><ul><li>${NETWORK_DEMO.alternatives[0].name}</li><li>${NETWORK_DEMO.alternatives[0].safety_state} / ${NETWORK_DEMO.alternatives[0].distance_km} km</li></ul></div>`; } }
async function runNetwork() { renderNetwork("loading"); await new Promise(resolve => setTimeout(resolve, 350)); if (USE_LIVE_API) { try { await liveJson("/network/build", { method: "POST", body: JSON.stringify({ records: [], max_distance_km: 10, source: "inline" }) }); await liveJson("/network/analyze", { method: "POST", body: JSON.stringify({ network_id: "network-demo-lake-1", alert_node_ids: ["node-upstream-1"] }) }); } catch (error) { renderNetwork("error", `${error.message}. Retry or continue with the offline demo.`); return; } } renderNetwork("ready"); }
function queueStatus(index) { if (beatIndex < 1) return ["pending", "PENDING"]; if (index < beatIndex - 1) return ["done", "DONE"]; if (index === beatIndex - 1) return ["in-progress", "IN PROGRESS"]; return ["pending", "PENDING"]; }
function queueMarkup() { const tasks = ["Verify source", "Sample suspect", "Confirm alternative"]; return `<div class="queue">${tasks.map((task, index) => { const [klass, label] = queueStatus(index); return `<div class="row"><span><b>${String(index + 1).padStart(2, "0")}</b> ${task}</span><label class="chip queue-status ${klass}">${label}</label></div>`; }).join("")}</div>`; }
function voiceMarkup() { return `<div class="voice-grid"><div class="payload"><small>SMS / ENGLISH</small><strong>DEMO LAKE WATER WATCH</strong><p>High harmful-algal-bloom signal. Do not swim, drink untreated water, or harvest food from the affected water. Keep people and animals away. Await field confirmation.</p></div><div class="payload"><small>SMS / CHICHEWA (CHI)</small><strong>CHENJEZO CHA MADZI A DEMO LAKE</strong><p>Chizindikiro cha ndere yoopsa chapezeka. Musasambe, musamamwe madzi osayeretsedwa, kapena kukolola chakudya m'madzi okhudzidwawo. Sungani anthu ndi ziweto kutali ndipo dikirani kutsimikiziridwa kwa ogwira ntchito m'munda.</p></div></div><div class="callout"><strong>Chipatala Cha Pa Foni / call-in script</strong><p><b>Chichewa demo:</b> "Moni, Chipatala Cha Pa Foni. Tikulandira chenjezo la madzi ku Demo Lake. Kodi pali odwala otsegula m'mimba kapena kusanza? Chonde nenani mudzi ndi nthawi yomwe zinayambira; musamwe madzi osayeretsedwa. Tithandiza kulumikiza chipatala ndi gulu la madzi."</p><p><b>English translation:</b> "Hello, Chipatala Cha Pa Foni. We have received a water alert for Demo Lake. Are there people with diarrhoea or vomiting? Please share the village and when it started; do not drink untreated water. We will connect you to the clinic and water team."</p></div>`; }
function timelineMarkup(showWeeks) { return `<div class="timeline"><div class="timeline-card"><small>ALERT</small><strong>22 SEP / screening signal</strong><p>Red alert issued for Demo Lake; community message and field queue opened.</p></div><div class="timeline-card"><small>ACTION</small><strong>Same day / verified-safe route</strong><p>Source verification, suspect sample, and alternative confirmation completed before escalation.</p></div>${showWeeks ? `<div class="timeline-card hit"><small>FOLLOWING WEEKS</small><strong>HIT / lead time 3 weeks</strong><p>Observed outcome matched the warning early enough for action. The response is recorded as a HIT.</p></div>` : ""}</div>${showWeeks ? `<div class="risk-feedback"><strong>MEMORY 2.0 → risk scoring</strong><br>Outcome feeds back into the risk score: verified hit + 3-week lead time becomes reusable evidence for the next Demo Lake alert.</div>` : ""}`; }
function renderBeat() { const flow = $("#presenter-flow"), panel = $("#beat-panel"), beat = PRESENTER_BEATS[Math.max(0, beatIndex)]; if (!beat) return; flow.hidden = false; $("#beat-counter").textContent = `BEAT ${beatIndex + 1} / ${PRESENTER_BEATS.length}`; let body = ""; if (beat.id === "voice") body = voiceMarkup(); else if (beat.id.startsWith("verify-source") || beat.id === "sample-suspect" || beat.id === "confirm-alternative") body = queueMarkup(); else body = timelineMarkup(beat.id === "memory"); panel.innerHTML = `<small>${beat.label}</small><h3>${beat.title}</h3><p class="beat-copy">${beat.copy}</p>${body}`; $("#next-beat").textContent = beatIndex === PRESENTER_BEATS.length - 1 ? "Restart presenter beats ↻" : "Next beat →"; }
async function runFullDemo() { if (demoRunning) return; demoRunning = true; const button = $("#demo-run"); button.disabled = true; button.textContent = "RUNNING…"; selectView("overview"); await runNetwork(); await new Promise(resolve => setTimeout(resolve, 250)); beatIndex = 0; renderBeat(); toast("DEMO RUN complete. VOICE step is ready."); button.disabled = false; button.textContent = "DEMO RUN"; demoRunning = false; }
function nextBeat() { beatIndex = beatIndex >= PRESENTER_BEATS.length - 1 ? 0 : beatIndex + 1; renderBeat(); }
async function init() { render(); $$(".nav").forEach(x => x.addEventListener("click", () => selectView(x.dataset.view))); $("#language").addEventListener("click", () => { language = language === "en" ? "sw" : "en"; render(); toast(language === "sw" ? "Swahili alert copy selected." : "English alert copy selected."); }); $("#refresh").addEventListener("click", async () => { render(await loadData()); toast(USE_LIVE_API ? "Live analysis refreshed." : "Offline demo is already current."); }); $("#network-demo").addEventListener("click", runNetwork); $("#demo-run").addEventListener("click", runFullDemo); $("#next-beat").addEventListener("click", nextBeat); $("#help").addEventListener("click", () => toast("Use DEMO RUN, then advance one presenter beat at a time.")); $("#alert-action").addEventListener("click", () => toast(DEMO_DATA.alerts[language].action)); $("#share").addEventListener("click", () => toast("Field note copied: keep people and animals away; confirm locally.")); $("#health-note").addEventListener("click", () => toast("Field note copied for the local health and water authority.")); }
document.addEventListener("DOMContentLoaded", init);
